In [1]:
import pandas as pd
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
print(type(iris.data))
print(iris.data)
print("-----")
print(type(iris.target))
print(iris.target)
print("-----")
print(type(iris.feature_names))
print(iris.feature_names)

<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3

In [3]:
# numpy配列をDataFrameにして見やすくする
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [4]:
# カラム追加
df["target"] = iris.target

In [5]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [6]:
# csvに書き込み
df.to_csv("iris.csv")

In [7]:
# csv読込
iris_csv = pd.read_csv("iris.csv")
iris_csv

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0             0                5.1               3.5                1.4   
1             1                4.9               3.0                1.4   
2             2                4.7               3.2                1.3   
3             3                4.6               3.1                1.5   
4             4                5.0               3.6                1.4   
..          ...                ...               ...                ...   
145         145                6.7               3.0                5.2   
146         146                6.3               2.5                5.0   
147         147                6.5               3.0                5.2   
148         148                6.2               3.4                5.4   
149         149                5.9               3.0                5.1   

     petal width (cm)  target  
0                 0.2       0  
1                 0.2       0  
2                 0.2       0  
3                 0.2       0  
4                 0.2       0  
..                ...     ...  
145               2.3       2  
146               1.9       2  
147               2.0       2  
148               2.3       2  
149               1.8       2  

[150 rows x 6 columns]

In [8]:
# csvに書き込み index=False にしてUnnamed: 0を出さない
df.to_csv("iris.csv", index=False)

In [9]:
# csv読込
iris_csv = pd.read_csv("iris.csv")
iris_csv

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

## pandas を使っているならば、import pickle は不要

DataFrameでも、それ以外のオブジェクトでも保存可能な pd.to_pickle

In [10]:
# df.to_pickle("保存ファイル名") これで書かれる例が多いが
# pd.to_pickle(オブジェクト名, "保存ファイル名") ← この書き方に統一した方がいい
pd.to_pickle(df, "iris.pkl")

In [11]:
# 理由
# これはエラー
a = [1,2,3]
a.to_pickle("a.pkl")

AttributeError: 'list' object has no attribute 'to_pickle'

In [12]:
# これは成功
pd.to_pickle(a, "a.pkl")

In [13]:
# 読み出し
hoge = pd.read_pickle("a.pkl")
hoge

[1, 2, 3]

In [14]:
# 読み出し
iris_df = pd.read_pickle("iris.pkl")
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]