In [1]:
import numpy as np

from sklearn.datasets import load_breast_cancer

In [2]:
cancer = load_breast_cancer()

print(cancer.data.shape)
print(cancer.data)
print("-"*100)
print(cancer.target.shape)
print(cancer.target)
print("-"*100)

(569, 30)
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
----------------------------------------------------------------------------------------------------
(569,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0

In [3]:
cancer.data[:, 0][cancer.target == 1]

array([13.54 , 13.08 ,  9.504, 13.03 ,  8.196, 12.05 , 13.49 , 11.76 ,
       13.64 , 11.94 , 11.52 , 13.05 ,  8.618, 10.17 ,  8.598,  9.173,
        9.465, 11.31 ,  9.029, 12.78 ,  8.888, 12.31 , 13.53 , 12.86 ,
       11.45 , 13.34 , 12.   , 12.36 , 14.64 , 14.62 , 13.27 , 13.45 ,
       12.18 ,  9.787, 11.6  ,  6.981, 12.18 ,  9.876, 10.49 , 11.64 ,
       12.36 , 11.34 ,  9.777, 12.63 , 14.26 , 10.51 ,  8.726, 11.93 ,
        8.95 , 11.41 , 14.5  , 13.37 , 13.85 , 15.1  , 12.19 , 15.71 ,
       11.71 , 11.43 , 11.28 ,  9.738, 11.43 , 12.9  , 10.75 , 11.9  ,
       14.95 , 14.44 , 13.74 , 13.   ,  8.219,  9.731, 11.15 , 13.15 ,
       12.25 , 16.84 , 12.06 , 10.9  , 11.75 , 12.34 , 14.97 , 10.8  ,
       14.97 , 12.32 , 11.08 , 10.66 ,  8.671,  9.904, 13.01 , 12.81 ,
       11.41 , 10.08 , 11.71 , 11.81 , 12.3  , 12.77 ,  9.72 , 12.91 ,
       12.23 , 12.47 ,  9.876, 13.11 , 15.27 , 11.84 , 11.89 , 10.2  ,
       13.65 , 13.56 , 10.18 , 13.27 , 14.34 , 10.44 , 15.   , 12.62 ,
      

In [4]:
len(cancer.target[cancer.target == 1])

357

In [5]:
len(cancer.target[cancer.target == 0])

212

In [6]:
len(cancer.data[:, 0][cancer.target == 1])

357

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [8]:
a[:][b==5]

array([2])

In [9]:
array = np.array([[1, 2, 3],[4, 5, 6]])  # 配列作成
print(array)
print(array.shape)  # 行列数
print(array.ndim)  # 次元数
print(array.size)  # 要素数
print(array.reshape(3, 2))  # ３行２列に
print(array.reshape(-1, 3))  # 3列のみ指定し、行は自動(-1)で
print(array.flatten())  # １次元に

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [10]:
print(np.arange(10))
print(np.arange(1, 10))
print(np.arange(1, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [11]:
print(np.zeros(6))
print(np.zeros((2, 3)))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
print(array_1 + array_2)  # 足し算では各要素が足されるだけ
print(np.append(array_1, array_2))  # 追加はnp.append関数を使う

[5 7 9]
[1 2 3 4 5 6]


In [13]:
array = np.arange(9).reshape(3, 3)
print(array)
print(array[0])  # 0行目
print(array[0][1])  # 0行1列目
print(array[0, 1])  # 0行１列目
print(array[:, 1])  # 全行1列目
print(array[-1, :]) #　最後の行全列

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
1
1
[1 4 7]
[6 7 8]


In [14]:
array = np.arange(9).reshape(3, 3)
print(array)
for i in array:  # 行の抽出
    print(i)
for i in array.flatten():  # 要素１つづつの抽出
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[3 4 5]
[6 7 8]
0
1
2
3
4
5
6
7
8


In [15]:
np.arange(0, 90, 10).reshape(3, 3)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [16]:
array = np.array([[0, 1, 2], [3, 4, 5]])
print(array)
print(np.sum(array))
print(np.sum(array, axis = 0))
print(np.sum(array, axis = 1))

[[0 1 2]
 [3 4 5]]
15
[3 5 7]
[ 3 12]


In [17]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([0, 1, 0, 1, 0])

print(y == 1)

print(x[y == 1])

[False  True False  True False]
[2 4]
