In [1]:
import numpy as np

In [2]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.random.randint(0, 101, (4))

array([ 0,  1,  6, 36])

In [5]:
a = [
    (b, c)
    for b in [1, 2]
    for c in [3, 4]
]

a

[(1, 3), (1, 4), (2, 3), (2, 4)]

In [6]:
a = []
for b in [1,2]:
    for c in [3,4]:
        a.append((b,c))
        
a


[(1, 3), (1, 4), (2, 3), (2, 4)]